name: Cleanup Deployment

on:
  workflow_run:
    workflows: [Deploy App]
    types:
      - completed

jobs:
  teardown:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'cancelled' }}
    steps:
      - uses: actions/checkout@v3

      - name: Workflow run event type
        run: echo ${{ toJSON(github.event.workflow_run) }}
