name: Dynamic Run name
run-name: ${{ github.event_name == 'workflow_dispatch' ? inputs.environment : 'auto' }}

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        default: dev
        options:
          - dev
          - stg
          - prod

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello world"

