name: Show error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo "::error file=app.js,line=1,col=5,endColumn=7::Error while running the script"
          exit 1
